[package]
name = "anzu"
version = "0.1.0"
authors = ["Eiji Akagi <akagi.eiji@gmail.com>"]
edition = "2018"

[dependencies]
rlibc = "1.0.0"

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

